### ISSUE TITLE
@sschoger/heroicons-ui isn't updated anymore

### ISSUE THREAD

**Issue by xerod** [Kholid060/vue-heroicons#39]
All the heroicon update is moved to [@refactoringui/heroicons](https://github.com/refactoringui/heroicons).

It has new solid styles and includes 140 icons (instead of 104). So there are several problems to fix:

- Move 140 sets of icons here, including the solid one
- Options for using outline or solid icons
- Change the whole documentation

**Comment by Kholid060** [comment]
Sorry for late reply, I'm no longer maintenance this repository. You can use https://github.com/matschik/vue-hero-icons instead.
